### ISSUE TITLE
Using pyDARNio on Windows Machine to convert bfiq to iqdat

### ISSUE THREAD

**Issue by Cooper10** [SuperDARN/pyDARNio#16]
issue is related to pytables and deepdish. 

I am trying to convert a bfiq file to an iqdat file with the following code:

import pydarn
import pydarnio

borealis_file = '20210113.2115.56.839612.inv.0.bfiq.hdf5'
sdarn_file = '20210113.2115.converted'
converter = pydarnio.BorealisConvert(borealis_file, 'bfiq', sdarn_file, 0, borealis_file_structure='array')

I successfully installed both pytables and deepdish on my machine and the error is related to .dll files.

The error is as follows: 

 'Could not load any of %s, please ensure that it %s.' % (hdf5_dlls, dll_loc))
ImportError: Could not load any of ['hdf5.dll', 'hdf5dll.dll', 'pytables_hdf5.dll'], please ensure that it can be found in the system path.

**Comment by carleyjmartin** [comment]
Deepdish is being depreciated from pyDARNio very soon as it is not being maintained, so this might solve itself. Sorry there was no movement on this issue, I'm going to close as stale but feel free for anyone to reopen if it remains an issue.
