### ISSUE TITLE
BorealisRead rawACF restructuring fails due to NaNs

### ISSUE THREAD

**Issue by alexchartier** [SuperDARN/pyDARNio#29]
# BUG 

Conversion of the Borealis rawacf hdf5 site files failed due to a NaN in the file. Tested using @RemingtonRohel's standard Borealis file and one of mine. 

## Priority

- [X] Major - misrepresentation of data, failure in a common situation 

Fails in Borealis data_flow's file conversion necessary for use of Borealis radar data by the wider SuperDARN community (e.g. RST etc.). 

## Example of the bug 

from pydarnio import BorealisRead
filename = '/home/radar/Downloads/20211006.2132.00.sas.0.rawacf.hdf5.site'
borealis_filetype = 'rawacf'
borealis_reader = BorealisRead(filename, borealis_filetype, borealis_file_structure='site')
arrays = borealis_reader.arrays

The file cannot be restructured due to the  following error: Records from /home/radar/Downloads/20211006.2132.00.sas.0.rawacf.hdf5.site: Error restructuring BorealisRawacfv0_5 from site to array style: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pydarnio-1.1.0-py3.8.egg/pydarnio/borealis/borealis_site.py", line 200, in arrays
  File "/usr/local/lib/python3.8/dist-packages/pydarnio-1.1.0-py3.8.egg/pydarnio/borealis/base_format.py", line 939, in _site_to_array
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_pdio.py", line 6, in <module>
    arrays = borealis_reader.arrays
  File "/usr/local/lib/python3.8/dist-packages/pydarnio-1.1.0-py3.8.egg/pydarnio/borealis/borealis.py", line 194, in arrays
  File "/usr/local/lib/python3.8/dist-packages/pydarnio-1.1.0-py3.8.egg/pydarnio/borealis/borealis_site.py", line 207, in arrays
pydarnio.exceptions.borealis_exceptions.BorealisRestructureError: The file cannot be restructured due to the  following error: Records from /home/radar/Downloads/20211006.2132.00.sas.0.rawacf.hdf5.site: Error restructuring BorealisRawacfv0_5 from site to array style: cannot convert float NaN to integer

### Attempts

Tried a couple of different files, same error each time. 

### Data Location

https://drive.google.com/drive/folders/1j37Ez6JY_IlNAYXx2kG6IGR3aWzhMNMi

## Potential Bug Location 

Not sure - either borealis.py, borealis_site.py or an error in SuperDARN Borealis radar format

## Potential Solution(s)
Not sure - either fix file write (outside pydarn scope) or Borealis rawacf site file read here in pyDARNio

## Extra Notes

*Please provide other pertinent details about this feature:*
Ubuntu Linux. Python 3.8

**Comment by RemingtonRohel** [comment]
Hi Alex,

I'm having trouble recreating your error. 

**Testing Script**

```python3
#!/bin/python3
# Trying to recreate bug from Alex Chartier: https://github.com/SuperDARN/pyDARNio/issues/29

from pydarnio import BorealisRead, BorealisWrite
filenames = ['/home/remington/sample_data/20211006.2132.00.sas.0.rawacf.hdf5.site',
             '/home/remington/sample_data/20211006.2200.01.wal.0.rawacf.hdf5.site']
outfile = ['/home/remington/sample_data/20211006.2132.00.sas.0.rawacf.hdf5',
           '/home/remington/sample_data/20211006.2200.01.wal.0.rawacf.hdf5']
borealis_filetype = 'rawacf'

for i in range(len(filenames)):
    borealis_reader = BorealisRead(filenames[i], borealis_filetype, 'site')
    arrays = borealis_reader.arrays

    borealis_writer = BorealisWrite(outfile[i], arrays, borealis_filetype, 'array')
```

**Output**

```
/home/remington/pyDARNio/venv/bin/python /home/remington/pydarnio_testing/test_restructuring.py

Process finished with exit code 0
```

**Software:** (Opensuse Leap 15.3, python 3.6)

```
(venv) remington@tabr~/pyDARNio$ pip list
Package         Version Location
--------------- ------- ------------------------
cached-property 1.5.2
deepdish        0.3.7
h5py            3.1.0
numexpr         2.7.3
numpy           1.19.5
pathlib2        2.3.6
pip             21.1.2
pydarnio        1.1.0   /home/remington/pyDARNio
PyYAML          6.0
scipy           1.5.4
setuptools      57.0.0
six             1.16.0
tables          3.6.1
wheel           0.36.2
```

**Comment by alexchartier** [comment]
@RemingtonRohel 
I still get my error when running your code. my pip list is a lot longer than yours, but I do not have "cached-property" 
I've upgraded everything that was older than your version to no effect. 
[piplist.txt](https://github.com/SuperDARN/pyDARNio/files/7487980/piplist.txt)

**Comment by RemingtonRohel** [comment]
@alexchartier 
Hmm, I don't know what the issue might be then. I tried removing cached-property, but it broke h5py.

```
/home/remington/pyDARNio/venv/bin/python /home/remington/pydarnio_testing/test_restructuring.py
Traceback (most recent call last):
  File "/home/remington/pyDARNio/venv/lib64/python3.6/site-packages/h5py/_hl/dataset.py", line 15, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/remington/pydarnio_testing/test_restructuring.py", line 4, in <module>
    from pydarnio import BorealisRead, BorealisWrite
  File "/home/remington/pyDARNio/pydarnio/__init__.py", line 43, in <module>
    from .borealis.borealis import BorealisRead
  File "/home/remington/pyDARNio/pydarnio/borealis/borealis.py", line 46, in <module>
    from .borealis_site import BorealisSiteRead, BorealisSiteWrite
  File "/home/remington/pyDARNio/pydarnio/borealis/borealis_site.py", line 39, in <module>
    import h5py
  File "/home/remington/pyDARNio/venv/lib64/python3.6/site-packages/h5py/__init__.py", line 60, in <module>
    from ._hl.files import (
  File "/home/remington/pyDARNio/venv/lib64/python3.6/site-packages/h5py/_hl/files.py", line 20, in <module>
    from .group import Group
  File "/home/remington/pyDARNio/venv/lib64/python3.6/site-packages/h5py/_hl/group.py", line 23, in <module>
    from . import dataset
  File "/home/remington/pyDARNio/venv/lib64/python3.6/site-packages/h5py/_hl/dataset.py", line 17, in <module>
    from cached_property import cached_property
ModuleNotFoundError: No module named 'cached_property'

Process finished with exit code 1
```

Would you be able to make a virtual environment and run your script from there? All I installed in my virtualenv was pydarnio, the rest were dependencies of it.

**Comment by alexchartier** [comment]
@RemingtonRohel yes - no difference. I'll poke around some more

**Comment by alexchartier** [comment]
ok, line to blame seems to be #939 in borealis/base_format.py:
empty_array[:] = np.NaN

I don't know how this whole section is supposed to work since we can't write NaNs to an "int" type (see e.g. here: 
https://stackoverflow.com/questions/11548005/numpy-or-pandas-keeping-array-type-as-integer-while-having-a-nan-value
)

My issue comes at the 'num_sequences' field, which has no dimensions. The num_records is 448. The datatype comes as int64 from the cls.single_element_types() dictionary. 

If you set the array up as it is in the code, it's guaranteed to fail:

empty_array = np.empty((448,),  dtype='int64')
empty_array[:] = np.NaN
*** ValueError: cannot convert float NaN to integer


I tried some changes to allow writing a NaN array (e.g. empty_array = np.ones(array_dims) * np.nan) but those cause a failure shortly after because the code is relying on type-setting to decide what to do next and the NaNs must be stored as float. 

There is some extension datatype in Pandas called 'Int64' (as opposed to 'int64') that might fix this, but I'm guessing there is some deeper problem that is causing all this.

**Comment by RemingtonRohel** [comment]
Ah, well this gets a little odd now. I can run that code snippet without the ValueError being raised, for whatever reason. What happens instead is that `empty_array` stays as type `int64` but all the data is changed to `-9223372036854775808`. I'm not finding any information on the internet about why this is happening. 

For num_sequences, I don't see any reason why the data needs to be initialized to nan. There is no padding of the num_sequences array, so every value should be overwritten by the correct number of sequences for the corresponding record. I think we could safely initialize empty_array to some value that would clearly be wrong, such as -1. 

The other integer field is num_slices, which also is initialized to `-9223372036854775808` when I run it. beam_nums and blanked_samples are 2d arrays, and get initialized to zeros by the line `empty_array[:] = np.NaN` when I run it.

Summary: All of the integer fields will eventually have non-negative data when filled, so I think it is safe to initialize them with -1 for all data points instead of np.NaN . This way we can bypass the problem and still tell if the data is bad.

**Comment by alexchartier** [comment]
OK, can you implement that or should I do it?

________________________________

**Comment by RemingtonRohel** [comment]
I can try it out, shouldn't take too long.

**Comment by RemingtonRohel** [comment]
Ah, I've overlooked a detail. `blanked_samples` and `beam_nums` are of type np.uint32, so initializing them to -1 causes overflow to a large number. I don't think it's too big of a deal, but I'm mentioning it here so there's a record of this.

Changes are in branch: https://github.com/SuperDARN/pyDARNio/tree/int_nan_cast

**Comment by alexchartier** [comment]
@RemingtonRohel I think I misunderstood the first time I read your comment. Are you saying it's good-to-go, and the overflow is not a big deal? If so I'll go ahead and test here.

**Comment by RemingtonRohel** [comment]
Sorry yes that was confusing! In my opinion it is good-to-go.
