### ISSUE TITLE
Multiple beams in a record

### ISSUE THREAD

**Issue by RemingtonRohel** [SuperDARN/pyDARNio#33]
# BUG 

When converting from HDF5 to DMAP, files with multiple beams in a record only have the last beam converted for each record. I'm not very familiar with the DMAP file standards, so I'm not sure how would be best to store multiple beams.

## Priority

- [x] Minor - typo, incorrect naming, fails on specific uncommon situation
- [ ] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Example of the bug 

Hard to show this in code, but when testing out a multiple-beam file with Dr. Pasha Ponomarenko, only the last beam made it from the HDF5 file to the DMAP file (rawacf files). 

### Attempts

Nothing yet

## Potential Bug Location 

Lines 590-757 and 855-1004 of borealis_convert.py (converting records: bfiq->iqdat, rawacf->dmap)

## Potential Solution(s)

Any beam-specific values will need to be extended for multiple beams, i.e. make it a list instead of just a number. I don't know what the implications will be downstream.

## Extra Notes

- OpenSuse Leap 15.3
- Python version 3.6

**Comment by RemingtonRohel** [comment]
After discussing with Dr. Pasha Ponomarenko, the proposed solution is to make a separate dictionary for each beam of a record, instead of just one dictionary per record.

**Comment by egthomas** [comment]
I'm not familiar with the dictionary terminology in relation to dmap-format files - do you mean the bmnum field will become an array and the relevant data arrays (acfd, xcfd, etc) will have their dimensionality increased? Or will there be multiple beam records with identical time stamps? Sorry for the confusion.

**Comment by RemingtonRohel** [comment]
Ah sorry I see now how that was confusing. pyDARNio makes a dictionary for each record that will be stored in a DMAP file, and these dictionaries get converted to DMAP format before being saved. When I said dictionary, I really meant each record.

So, for the fix that I'm working on, there will be multiple beam records with identical time stamps. This seems like an easier solution than having to change the dimensionality of the relevant fields in _all_ records. I have made a branch with some commits that I'm currently testing out: https://github.com/SuperDARN/pyDARNio/tree/multi-beam_conversion

**Comment by egthomas** [comment]
Ok that sounds great, thanks!
